/**
 * Writes supabase/tests/16_access_snapshot.test.sql: the approved list of what anon and
 * authenticated may do (RLS, table/column privileges, policies, function EXECUTE), read from the
 * local Supabase database. Run it after a migration that changes access on purpose, then review the
 * diff of the test file in the PR: every added line is new access someone is approving.
 *
 *   pnpm db:access-snapshot          (local stack running: `supabase start`)
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(__dirname, "..", "..");
const query = readFileSync(join(__dirname, "access-snapshot.sql"), "utf8");
const container = process.env.SUPABASE_DB_CONTAINER ?? "supabase_db_mezza";

const out = execFileSync(
  "docker",
  ["exec", "-i", container, "psql", "-U", "postgres", "-d", "postgres", "-At", "-v", "ON_ERROR_STOP=1"],
  {
    input: query,
    encoding: "utf8",
  },
);
const lines = out
  .split("\n")
  .map((l) => l.trimEnd())
  .filter(Boolean);
const quote = (s: string) => `('${s.replaceAll("'", "''")}')`;

const test = `-- GENERATED by \`pnpm db:access-snapshot\` (scripts/db/access-snapshot.ts). Do not edit by hand.
-- The approved list of what anon and authenticated may do. A migration that grants, revokes or changes
-- a policy fails this test until the snapshot is regenerated, so the access change shows up in review.
begin;
select no_plan();

create temporary table approved (line text primary key);
insert into approved values
${lines.map(quote).join(",\n")};

create temporary table actual as
${query
  .replace(/^--.*\n/gm, "")
  .trim()
  .replace(/;$/, "")};

select diag('not approved: ' || line) from (select line from actual except select line from approved) x;
select diag('approved but gone: ' || line) from (select line from approved except select line from actual) x;
select is((select count(*) from (select line from actual except select line from approved) x), 0::bigint,
  'no access beyond the approved snapshot');
select is((select count(*) from (select line from approved except select line from actual) x), 0::bigint,
  'every approved access still exists (after an intended change: pnpm db:access-snapshot)');

select * from finish();
rollback;
`;
writeFileSync(join(root, "supabase", "tests", "16_access_snapshot.test.sql"), test);
console.log(`approved ${lines.length} access lines -> supabase/tests/16_access_snapshot.test.sql`);
